<?php

declare(strict_types=1);

use App\Actions\User\GetAvatarAction;
use App\Events\MessageReceived;
use App\Models\Message;
use App\Models\User;
use Illuminate\Broadcasting\PrivateChannel;
use Illuminate\Foundation\Testing\RefreshDatabase;

uses(RefreshDatabase::class);

beforeEach(function () {
    $this->user = User::factory()->create();
    $this->forUser = User::factory()->create();
    $this->message = Message::factory()->create([
        'user_id' => $this->user->id,
    ]);
    $this->event = new MessageReceived($this->message, $this->forUser);
});

it('can be instantiated with message and user', function () {
    expect($this->event)->toBeInstanceOf(MessageReceived::class);
    expect($this->event->message)->toBe($this->message);
    expect($this->event->forUser)->toBe($this->forUser);
});

it('broadcasts on the correct private channel', function () {
    $channels = $this->event->broadcastOn();

    expect($channels)->toHaveCount(1);
    expect($channels[0])->toBeInstanceOf(PrivateChannel::class);
    expect($channels[0]->name)->toBe("private-user.{$this->forUser->id}");
});

it('broadcasts with the correct event name', function () {
    expect($this->event->broadcastAs())->toBe('message.sent');
});

it('broadcasts with the correct data structure', function () {
    $broadcastData = $this->event->broadcastWith();

    expect($broadcastData)->toHaveKeys(['message', 'conversation_id']);

    // Test message structure
    $messageData = $broadcastData['message'];
    expect($messageData)->toHaveKeys(['id', 'content', 'type', 'metadata', 'created_at', 'user']);
    expect($messageData['id'])->toBe($this->message->id);
    expect($messageData['content'])->toBe($this->message->content);
    expect($messageData['type'])->toBe($this->message->type);
    expect($messageData['metadata'])->toBe($this->message->metadata);
    expect($messageData['created_at'])->toEqual($this->message->created_at);

    // Test user structure within message
    $userData = $messageData['user'];
    expect($userData)->toHaveKeys(['id', 'name', 'avatar_url']);
    expect($userData['id'])->toBe($this->user->id);
    expect($userData['name'])->toBe($this->user->name);

    // Test conversation_id
    expect($broadcastData['conversation_id'])->toBe($this->message->conversation_id);
});

it('includes avatar URL from GetAvatarAction', function () {
    $broadcastData = $this->event->broadcastWith();
    $userData = $broadcastData['message']['user'];

    // The avatar URL should be generated by GetAvatarAction
    $expectedAvatarUrl = (new GetAvatarAction())->handle($this->user);
    expect($userData['avatar_url'])->toBe($expectedAvatarUrl);
});

it('handles different message types correctly', function () {
    $textMessage = Message::factory()->create([
        'user_id' => $this->user->id,
        'type' => 'text',
        'content' => 'Hello world'
    ]);

    $imageMessage = Message::factory()->create([
        'user_id' => $this->user->id,
        'type' => 'image',
        'content' => 'image.jpg'
    ]);

    $fileMessage = Message::factory()->create([
        'user_id' => $this->user->id,
        'type' => 'file',
        'content' => 'document.pdf'
    ]);

    foreach ([$textMessage, $imageMessage, $fileMessage] as $message) {
        $event = new MessageReceived($message, $this->forUser);
        $broadcastData = $event->broadcastWith();

        expect($broadcastData['message']['type'])->toBe($message->type);
        expect($broadcastData['message']['content'])->toBe($message->content);
    }
});

it('handles messages with metadata correctly', function () {
    $messageWithMetadata = Message::factory()->create([
        'user_id' => $this->user->id,
        'metadata' => ['file_size' => 1024, 'mime_type' => 'image/png']
    ]);

    $event = new MessageReceived($messageWithMetadata, $this->forUser);
    $broadcastData = $event->broadcastWith();

    expect($broadcastData['message']['metadata'])->toBe($messageWithMetadata->metadata);
});

it('handles messages with null metadata correctly', function () {
    $messageWithoutMetadata = Message::factory()->create([
        'user_id' => $this->user->id,
        'metadata' => null
    ]);

    $event = new MessageReceived($messageWithoutMetadata, $this->forUser);
    $broadcastData = $event->broadcastWith();

    expect($broadcastData['message']['metadata'])->toBeNull();
});

it('broadcasts to different users correctly', function () {
    $user1 = User::factory()->create();
    $user2 = User::factory()->create();

    $event1 = new MessageReceived($this->message, $user1);
    $event2 = new MessageReceived($this->message, $user2);

    $channels1 = $event1->broadcastOn();
    $channels2 = $event2->broadcastOn();

    expect($channels1[0]->name)->toBe("private-user.{$user1->id}");
    expect($channels2[0]->name)->toBe("private-user.{$user2->id}");
});

it('implements the correct interfaces', function () {
    expect($this->event)->toBeInstanceOf(\Illuminate\Contracts\Broadcasting\ShouldBroadcastNow::class);
});

it('has the correct traits', function () {
    $traits = class_uses(MessageReceived::class);

    expect($traits)->toContain(\Illuminate\Foundation\Events\Dispatchable::class);
    expect($traits)->toContain(\Illuminate\Broadcasting\InteractsWithSockets::class);
    expect($traits)->toContain(\Illuminate\Queue\SerializesModels::class);
});

it('maintains data consistency with message relationship', function () {
    // Create a message with a known conversation
    $conversation = \App\Models\Conversation::factory()->create();
    $messageWithConversation = Message::factory()->create([
        'user_id' => $this->user->id,
        'conversation_id' => $conversation->id,
    ]);

    $event = new MessageReceived($messageWithConversation, $this->forUser);
    $broadcastData = $event->broadcastWith();

    expect($broadcastData['conversation_id'])->toBe($conversation->id);
    expect($broadcastData['message']['id'])->toBe($messageWithConversation->id);
});

it('works with fresh message instances', function () {
    // Test that the event works with freshly created messages
    $freshMessage = Message::factory()->create(['user_id' => $this->user->id]);
    $freshUser = User::factory()->create();

    $event = new MessageReceived($freshMessage, $freshUser);
    $broadcastData = $event->broadcastWith();

    expect($broadcastData['message']['id'])->toBe($freshMessage->id);
    expect($broadcastData['conversation_id'])->toBe($freshMessage->conversation_id);

    $channels = $event->broadcastOn();
    expect($channels[0]->name)->toBe("private-user.{$freshUser->id}");
});