blank_issues_enabled: true
contact_links:
  - name: "Create Issue without Template"
    url: "https://github.com/hunter-cv/web/issues/new?template=&title=&body="
    about: "Skip the template and open a blank issue directly"